{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "invidious.name" . }}-ingress
  namespace: invidious
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass }}
    {{- if  .Values.ingress.certManager.enabled -}}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
    {{- end -}}
    {{- if .Values.ingress.ingressClass == "traefik" -}}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," .Values.ingress.middlewares }}
    {{- end -}}
    {{- if .Values.ingress.externalDns.enabled -}}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.domain }}
    external-dns.alpha.kubernetes.io/ttl: {{ .Values.ingress.externalDns.ttl }}
    {{- end -}}
    {{- with .Values.ingress.annotations -}}
    {{- toYaml . | indent 8 -}}
    {{- end -}}
  labels:
    app: {{ template "invidious.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "invidious.name" . }}
                port:
                  number: {{ .Values.service.port }}
                
  tls:
    - secretName: {{ template "invidious.name" . }}-tls
      hosts:
        - {{ .Values.ingress.domain }}
{{- end -}}