{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "invidious.fullname" . }}-secret
  labels:
    app: {{ template "invidious.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  db_values: {{ .Values.secret.db | b64enc }}
  hmac_key: {{ randAlphaNum | b64enc }}
{{- end -}}