apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon-glitch
  namespace: selfhosted
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: mastodon
      version: '>=4.0.0'
      sourceRef:
        kind: GitRepository
        name: mastodon
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: mastodon-glitch-helm-chart-value-overrides
    valuesKey: values.yaml 