apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-postgtres-creds
  namespace: selfhosted
spec:
  encryptedData:
    password: AgBOxuG8RDHmjOvIHCkJwbOF2DLpfyBaxbJN9t+E+OQP8jP6iZPOtlUNfxPsMe3U2VvltjbW0BAtCnLA9/WNWiphLux3aL5FbbMZnzaePivGtlnxiQgqHTJ6JACzWkZjESXY8Vq/KBN1RM/WHSStZ4fUI4fu48zV62ahP89duk6M32zfega/oRCaUDNnifGW9lc3zBMprvdg5jCVsgcVNeg+zM1dKlQAMOwkUFpbYuHRoRgwox88f8efj7BvQdEviyoiHsyp/dqCJFzlBNTvh1zEQfB4g+5MZwWOvpExkCGCf5vZqLhPr6fkdtW5F6lZg37ODhL+8Hz4QM+GPlTiVZUxyaXnloGCZI3wxMvt+5+PBQHCihsV0s9N2Z1sBqJhM5cAHyEL5y3ou6rUyByT7tC0tQoYh8mH2HxyUiEw8FFE5pL1BZx/7ZsGsOVTKBMusjuxJm5R3nl2mi6/q1xWnwP4qdNLntbOVJ2PODUIFljc4eiG7wmRYDUi2JZdPZzNziAnet5BrT+O4kt4GjFh9qZKU4GjXz1vNWObp47EChzHG5kOGSrwAv3HTMWECQBHW1gcN/zEz0sdpGsJ5q59KHPthRvy6YLIVdknOpfLyFwPtpsBj0VBq2VCaanojehfMuvwxbguVXkZdco95Nz9ARmoVFeLAhQaZOKaDj5KOzASN9k9XimSSdebcL//KPl0LvPVRCsxBs7kFhK8RrcM1p8M6OjA56oXT5w=
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-postgtres-creds
      namespace: selfhosted

