apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teddit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: '>=1.0.0'
  interval: 1h0m0s
  releaseName: teddit
  targetNamespace: selfhosted
  values:
    image:
      # -- image repository
      repository: teddit/teddit
      # -- image pull policy
      pullPolicy: Always
      # -- image tag
      # this example is not automatically updated, so be sure to use the latest image
      tag: latest
    controller:
      strategy: "RollingUpdate"
      replicas: 3
    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/hostname: "teddit.thekitty.zone"
          external-dns.alpha.kubernetes.io/ttl: "600" #optional
        ingressClassName: ""
        enabled: true
        hosts:
          - host: teddit.thekitty.zone
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8080
        tls:
          - secretName: teddit-thekitty.zone-tls
            hosts:
              - teddit.thekitty.zone
    env:
      DOMAIN: teddit.thekitty.zone
      API_FORCE_HTTPS: true
      REDIS_HOST: redis-master
      REDIS_PORT: 6379
      USE_HELMET: true
      USE_HELMET_HSTS: true
      TRUST_PROXY: true