apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  chart: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: monitoring
  values:
    alertmanager:
      config:
        route:
          group_by: ['alertname','job', 'servity']
          group_wait: 20s
          group_interval: 5m
          repeat_interval: 3h 
          receiver: discord_webhook

        receivers:
        - name: 'null'
        - name: 'discord_webhook'
          webhook_configs:
          - url: 'http://alertmanager-discord:9094'

    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: hcloud-volumes
              accessModes: 
              - "ReadWriteOnce"
              resources:
                requests:
                  storage: 20Gi
        retention: 10d
        scrape_configs:
        - job_name: 'crunchy-postgres-exporter'
          kubernetes_sd_configs:
          - role: pod

          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_crunchy_postgres_exporter,__meta_kubernetes_pod_label_crunchy_postgres_exporter]
            action: keep
            regex: true
            separator: ""
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: drop
            regex: 5432
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: drop
            regex: 10000
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: drop
            regex: 8009
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: drop
            regex: 2022
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: drop
            regex: ^$
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_cluster,__meta_kubernetes_pod_label_pg_cluster]
            target_label: cluster
            separator: ""
            replacement: '$1'
          - source_labels: [__meta_kubernetes_namespace,cluster]
            target_label: pg_cluster
            separator: ":"
            replacement: '$1$2'
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: ip
            replacement: '$1'
          - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance,__meta_kubernetes_pod_label_deployment_name]
            target_label: deployment
            replacement: '$1'
            separator: ""
          - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role,__meta_kubernetes_pod_label_role]
            target_label: role
            replacement: '$1'
            separator: ""
          - source_labels: [dbname]
            target_label: dbname
            replacement: '$1'
          - source_labels: [relname]
            target_label: relname
            replacement: '$1'
          - source_labels: [schemaname]
            target_label: schemaname
            replacement: '$1'
    kubeControllerManager:
      enabled: true
      endpoints:
      - 10.253.0.101
      - 10.254.0.101
      - 10.255.0.101
    kubeEtcd:
      enabled: true
      endpoints:
      - 10.253.0.101
      - 10.254.0.101
      - 10.255.0.101
      service:
        enabled: true
        port: 2381
        targetPort: 2381
    kubeScheduler:
      enabled: true
      endpoints:
      - 10.253.0.101
      - 10.254.0.101
      - 10.255.0.101
    kubeProxy:
      enabled: true
      endpoints:
      - 10.253.0.101
      - 10.254.0.101
      - 10.255.0.101

    grafana:
      forceDeployDatasources: true
      forceDeployDashboards: true
      sidecar:
        datasources:
          enabled: true
          defaultDatasourceEnabled: true
          isDefaultDatasource: true
          uid: prometheus
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki:3100
          editable: true
      serviceMonitor:
        enabled: true
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: hcloud-volumes
        accessModes:
          - ReadWriteOnce
      grafana.ini:
        feature_toggles:
          publicDashboards: true