---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grocy
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/homepageAndBlog/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: apps/v1
      kind: HelmRelease
      name: grocy
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: barcode-buddy
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/homepageAndBlog/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: apps/v1
      kind: HelmRelease
      name: barcode-buddy
      namespace: flux-system
  wait: true
  dependsOn:
    - name: grocy