- hosts: webservers
  become: true
  tasks:
  - name: Upload docker compose file
    template:
      src: ../keysAndConfs/api/docker-compose.yml
      dest: /root/docker-compose.yml
      owner: root
      group: root
      mode: '0644'
  - name: Pull images
    ansible.builtin.shell: docker-compose pull
  - name: Stop container
    ansible.builtin.shell: docker-compose down
  - name: Start container
    ansible.builtin.shell: docker-compose up -d
    