- hosts: webservers
  become: true
  tasks:
  - name: Install Docker
    ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    notify: restart docker
  - name: Install docker-compose from official github repo
    get_url:
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
  
  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted