- hosts: webservers
  become: true
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: ../keysAndConfs/site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: copy nginx api.conf
    template:
      src: ../keysAndConfs/api.conf.j2
      dest: /etc/nginx/sites-enabled/{{ api_domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted