- hosts: webservers
  become: true
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist