{
 "title": "Global MPW Instances",
 "description": "An 'aggregation' of statistics from ALL global MPW instances that allow Labs Analytics.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(hits[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(hits[$__rate_interval])) by (mpw_instance)",
     "legendFormat": "{{mpw_instance}}"
    }
   ]
  },
  {
   "title": "User Browsers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(browser) (changes(hits[$__interval]))",
     "legendFormat": "{{browser}}"
    }
   ]
  },
  {
   "title": "Time to Sync (per-instance) in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "time_to_sync{job=\"mpw\"}",
     "legendFormat": "Explorer: {{explorer}} Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(transactions[$__interval]))#TIL: Comments in Grafan -Zozo 22/09/29 21:37 ",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "User devices",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hits) by (device)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Prometheus uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": " quantile(0.95, min_over_time(up [$__interval])) ",
     "legendFormat": "Uptime"
    }
   ]
  }
 ]
}