- hosts: servers
  become: true
  tasks:
  - name: UFW Allow ceph cluster communication
    ufw: from_ip={{hostvars[item]['internal_ip']}} rule=allow
    with_items: "{{hostvars}}"
    when: hostvars[item]['internal_ip'] is defined

  - name: UFW Allow ceph mon access from ceph nodes
    ufw: from_ip={{hostvars[item]['internal_ip']}} rule=allow port=3300,6789 proto=tcp
    with_items: "{{hostvars}}"
    when: hostvars[item]['internal_ip'] is defined

  - name: UFW Allow ceph services access from ceph nodes
    ufw: from_ip={{hostvars[item]['internal_ip']}} rule=allow port=6800:7300 proto=tcp
    with_items: "{{hostvars}}"
    when: hostvars[item]['internal_ip'] is defined

  - name: UFW Allow ceph rgw access from ceph nodes
    ufw: from_ip={{hostvars[item]['internal_ip']}} rule=allow port=8000 proto=tcp
    with_items: "{{hostvars}}"
    when: hostvars[item]['internal_ip'] is defined

  - name: UFW Allow prometheus monitoring from monitoring vm
    ufw: from_ip={{hostvars[item]['internal_ip']}} rule=allow port=9100,9283,9093,9094,9095 proto=tcp
    with_items: "{{hostvars}}"
    when: hostvars[item]['internal_ip'] is defined

  - name: UFW Allow loki access from monitoring vm
    ufw: from_ip={{hostvars[item]['internal_ip']}} rule=allow port=3100,8080 proto=tcp
    with_items: "{{hostvars}}"
    when: hostvars[item]['internal_ip'] is defined
  
  - name: UFW Allow SSH access from NETCUP
    ufw: rule=allow port=22 proto=tcp

  - name: UFW Allow ceph rgw access from NETCUP
    ufw: from_ip={{netcup_server}} rule=allow port=8000,8001 proto=tcp
  
  - name: UFW Allow ceph dashboard,grafana,alertmanager,prometheus access from NETCUP
    ufw: from_ip={{netcup_server}} rule=allow port=8443,3000,9093,9094,9095 proto=tcp
    when: hostvars[inventory_hostname]['admin']|default(false)|bool  == true

  - name: UFW Disllow ceph dashboard,grafana,alertmanager,prometheus access
    ufw: rule=deny port=8443,3000,9093,9094,9095 proto=tcp
    when: hostvars[inventory_hostname]['admin']|default(false)|bool  != true
