---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 10m
  path: "./infrastructure/kubernetes/deployments/proxitok/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: signer
  namespace: flux-system
spec:
  interval: 10m
  path: "./infrastructure/kubernetes/deployments/proxitok/signer"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: signer
      namespace: flux-system
  wait: true
  dependsOn:
  - name: redis
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: proxitok
  namespace: flux-system
spec:
  interval: 10m
  path: "./infrastructure/kubernetes/deployments/proxitok/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: proxitok
      namespace: flux-system
  wait: true
  dependsOn:
  - name: redis
  - name: signer