
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
  labels:
spec:
  interval: 1h0m0s
  path: "./deployments/vaultwarden/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  wait: true