apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: inv-in-flight-limit
  namespace: invidious
spec:
  inFlightReq:
    amount: 100
    sourceCriterion:
      requestHost: true