apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: inv-ratelimit
  namespace: invidious
spec:
  rateLimit:
    average: 100
    burst: 50
    sourceCriterion:
      requestHost: true