
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/vaultwarden/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: apps/v1
      kind: HelmRelease
      name: vaultwarden
      namespace: vaultwarden
  wait: true