apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: collar-rs-client
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: collar-rs-client
  filterTags:
    pattern: '^(?P<ts>.*)-[a-fA-F0-9]+'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc