apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: homepage
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homepage
  filterTags:
    pattern: '^(?P<ts>.*)-[a-fA-F0-9]+'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc