apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mastodon
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mastodon
  filterTags:
    pattern: '^[0-9a-f]{5,40}\b'
  policy:
    alphabetical:
      order: asc