apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: signer
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: signer
  filterTags:
    pattern: '^sha256-[a-fA-F0-9]+.sig'
  policy:
    alphabetical:
      order: asc