---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: fluentbit
  namespace: monitoring
spec:
  chart: 
  repo:  
  targetNamespace: monitoring
  valuesContent: |-
serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 10s
  scrapeTimeout: 10s
  jobLabel: fluentbit
  selector:
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/name: fluentbit
config:
  inputs: |-
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
    [INPUT]
        Name tail
        Tag traefik
        Path /var/log/containers/kube-system_traefik*.log,
        Parser docker
        DB /var/log/flb_traefik.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        Refresh_Interval 1
  outputs: |-
    [OUTPUT]
        Name loki
        match traefik.*
        host loki.monitoring.svc.cluster.local 
        port 3100
        tenant_id ""
        labels job=fluentbit
        auto_kubernetes_labels on
        line_format json
  filters: |-
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
    [FILTER]
        Name geoip2
        Match traefik
        Database /etc/fluent-bit/GeoLite2-City.mmdb
        Lookup_key traefik.ClientHost
        Record country traefik.ClientHost %{country.names.en}
        Record isocode traefik.ClientHost %{country.iso_code}
        Record city    traefik.ClientHost %{city.names.en}
        Record latitude traefik.ClientHost %{location.latitude}
        Record longitude traefik.ClientHost %{location.longitude}
        Record postal_code traefik.ClientHost %{postal.code}
        Record region-code traefik.ClientHost %{subdivisions.0.iso_code}
        Record region-name traefik.ClientHost %{subdivisions.0.names.en}
  parsers: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
    
    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc/fluent-bit.conf
    subPath: fluent-bit.conf
  - name: config
    mountPath: /fluent-bit/etc/custom_parsers.conf
    subPath: custom_parsers.conf
dashboards:
  enabled: true
  labelKey: grafana_dashboard
  annotations: {}
  namespace: monitoring
daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File
  - name: geoip2
    hostPath:
      path: /etc/fluent-bit/GeoLite2-City.mmdb

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true
  - name: geoip2
    mountPath: /etc/fluent-bit/GeoLite2-City.mmdb
    readOnly: true
