---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: '>1.0.0'
  interval: 1h0m0s
  releaseName: redis
  targetNamespace: proxitok
  values:
    auth:
      ## @param auth.enabled Enable password authentication
      ##
      enabled: true
      ## @param auth.existingSecret The name of an existing secret with Redis&reg; credentials
      ## NOTE: When it's set, the previous `auth.password` parameter is ignored
      ##
      existingSecret: "secret-redis"
      ## @param auth.existingSecretPasswordKey Password key to be retrieved from existing secret
      ## NOTE: ignored unless `auth.existingSecret` parameter is set
      ##
      existingSecretPasswordKey: "redis_auth_key"
    metrics:
      ## @param metrics.enabled Start a sidecar prometheus exporter to expose Redis&reg; metrics
      ##
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: "monitoring"
    master:
      persistence:
        sizeLimit: 11Gi
        size: 10Gi