---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./namespace.yaml
  - ./ingress
  - ./podMonitors
  - ./serviceMonitors
  - ./dashboards
  - ./alertmanager-discord.yaml