---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/monitoring/prometheus"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/monitoring/loki"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  wait: true
  dependsOn:
    - name: prometheus