---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: lbry
  namespace: flux-system
spec:
  interval: 10m
  path: "./infrastructure/kubernetes/deployments/librarian/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: lbry
      namespace: flux-system
  wait: true