apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgA8naIXvl1oXP36NcvD4BloMnmQoGixIn23yGCdghOL0UDWXCNtcwQWmBRO7pprIpbSIRqwWBFGN7Gx0vsVwgCF3drOdnlk2tmjYINu8L3lNQhA7AtUHJX+L6DEQRNYxFAzix9nIYSzTo76zSlFuBYdVjJ7R5wSQBBNDBesW2fZKj726+g/cY8LGDAICUAQSqd2eFDQkJB5IBBwQp9X6kQGS00yhDooY04ERhvFwqvGaz0FwLmkL7aafG2EVZgbpYuohkE6aTjkYYTNXPBRXQ6g+l0uPvjp0FHx/c/VIhqTycSWf1J6YRwVcedt56Jn7R1e8MwqrGFmoHuinHHrvCrKUkjUIVy5Ola9q/vHx6ESDY+2QlF27JTG8/KkB+z0zCtPneTVKWCCiexj4qRDFJz/ld857FjIV1XKAl/3CV4cT648ECkLf1ZX6oSh5w4qO/9ITpd48WXL3UacSAJZdGLoGzCvr15Xj2ZkeDLHGa7xjMYQ0apmlutCm4vR9AfuBba7MrZbWVHmd1s3G8ANy9OLzDgy/OzkOjYczfxUGRapmpBckm9yHiJV/NSM3QkIYcatyw2vUpzzoB/YF+/rUzIj6Csx2p1AcD8h0d1N7q/iOYoSbqz5Y7zHpOhdEupalw3bbfUa7scqDAbEtnoRfZOnIinKc1D7RBNeqcofsRUV8DToX9W25x0slqoZ/rpAXSLS5TRv3B60H8ZpoAJTABKlf5h+jI//CpawCoEUUt0m+2LOC81/6D8U
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system
