apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  address: https://github.com/TheKitty-zone/k3s-infra
  secretRef:
    name: github