---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: invidious
resources:
  - ./namespace.yaml
  - ./sealed-secret-invidious.yaml
  - ./helmrelease.yaml
  - ./invInFlightLimit.yaml
  - ./invRateLimit.yaml
