---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/traefik/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  wait: true