apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./firefly.yaml
  - ./home-repo.yaml
  - ./sealed-secrets.yaml
  - ./mastodon.yaml
  - ./tyzbit.yaml