apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/FyraLabs/chart
  ref:
    branch: main