---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: '>=2.7.0-0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
  values:
    metrics:
      serviceMonitor:
        enabled: true
        namespace: monitoring
      dashboards:
        create: true
        namespace: monitoring

