apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: monitoring
spec:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  targetNamespace: monitoring
  valuesContent: |-
      loki:
        persistence:
          enabled: true
          storageClassName: "csi-cephfs-sc"
          # Customize this
          size: 100Gi
        config:
          table_manager:
            retention_deletes_enabled: true
            # Customize this: how long should logs be kept?
            retention_period: 30d
          limits_config:
            max_query_series: 5000
        serviceMonitor:
          enabled: true
          namespace: monitoring

      promtail:
        enabled: true
      fluent-bit:
        enabled: false
