apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: elefant
  namespace: postgres-operator
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-1
  postgresVersion: 14
  instances:
    - name: instance1
      replicas: 4
      dataVolumeClaimSpec:
        storageClassName: "hcloud-volumes"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 120Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: elefant-ha
                  postgres-operator.crunchydata.com/instance-set: pgha1
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-s3-uri-style: path
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-path: /pgbackrest/postgres-operator/elefant/repo1
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          differential: "0 1 * * 1-6"
        s3:
          bucket: "k3s-pgo-backup"
          endpoint: "https://s3.ceph.thekitty.zone"
          region: "CEPH_AINT_NO_NEED_REGION"
  users:
    - name: postgres
    - name: matrix
      databases:
      - matrix
    - name: nextcloud
      databases:
      - nextcloud
    - name: kemal
      databases:
        - invidious
    - name: vaultwarden
      databases:
        - vaultwarden
    - name: firefly
      databases:
        - firefly
    - name: mastodon
      databases:
        - mastodon_production
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.1-0
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-1
      replicas: 4
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: elefant
                  postgres-operator.crunchydata.com/role: pgbouncer
  patroni:
    dynamicConfiguration:
      synchronous_mode: false
      synchronous_mode_strict: false
      max_wal_size: 8GB
      autovacuum_vacuum_cost_limit: 1000
      autovacuum_vacuum_cost_delay: 10ms
      autovacuum_naptime: 5s
      vacuum_freeze_table_age: 100000
      vacuum_freeze_min_age: 100000
      track_activity_query_size: 2048
      autovacuum_freeze_max_age: 100000
      pg_stat_statements.track: all
      max_connections: 5000
      keepalives_idle: 30
      tcp_keepalives_idle: 30
