---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  type: oci
  interval: 60m0s
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: weave-gitops
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
      interval: 12h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
      username: admin
      passwordHash: "$2b$12$jSOeUuNF6Bsht83Q/VsKquB4ZvXsm5PU/1fmCON4H92t/tjv.Y9YG"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-gitops
  namespace: flux-system
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: "flux.thekitty.zone"
    external-dns.alpha.kubernetes.io/ttl: "3600" #optional
spec:
  rules:
  - host: flux.thekitty.zone
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: weave-gitops
            port: 
              number: 9100
  tls:
    - secretName: flux-thekitty.zone-tls
      hosts:
        - flux.thekitty.zone
