---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: firefly
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/home/firefly"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: firefly
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grocy
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/home/grocy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: grocy
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/vaultwarden"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: apps/v1
      kind: HelmRelease
      name: vaultwarden
      namespace: home
  wait: true