---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crypt-pad
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/cryptpad"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: crypt-pad
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: homepage-blog
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/homepageAndBlog"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: homepage-blog
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: invidious
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/invidious"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: invidious
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: lbry
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/librarian"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: lbry
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: libreddit
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/libreddit"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: libreddit
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mpw
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/mpw"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mpw
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-configs
  path: "./apps/base/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: signer
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/base/signer"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: signer
      namespace: flux-system
  wait: true
  dependsOn:
  - name: infra-configs
  - name: redis
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: proxitok
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/base/proxitok"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: proxitok
      namespace: flux-system
  wait: true
  dependsOn:
  - name: infra-configs
  - name: redis
  - name: signer
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rimgo
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
  - name: infra-configs
  path: "./apps/base/rimgo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rimgo
      namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: searxng
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
  - name: infra-configs
  path: "./apps/base/searx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: searxng
      namespace: flux-system
  wait: true