---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  path: "./infrastructure/kubernetes/deployments/traefik/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traefik
      namespace: kube-system
  wait: true