---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Replace the email address with your own contact email
    email: zofi@xamh.de
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: "cloudflare@xamh.de"
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - 'thekitty.zone'
        - '*.thekitty.zone'