---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      reconcileStrategy: Revision
      chart: loki-stack
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: '>=1.0.0'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h0m0s
  releaseName: loki
  targetNamespace: monitoring
  values:
      loki:
        persistence:
          enabled: true
          storageClass: "hcloud-volumes"
          # Customize this
          size: 12Gi
        config:
          table_manager:
            retention_deletes_enabled: true
            # Customize this: how long should logs be kept?
            retention_period: 1w
          limits_config:
            max_query_series: 5000
        serviceMonitor:
          enabled: true

      promtail:
        enabled: true
      fluent-bit:
        enabled: false
