---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rimgo
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/rimgo/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  wait: true
