apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neko
  namespace: flux-system
spec:
  chart:
    spec:
      chart: neko
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 1h0m0s
  releaseName: neko
  targetNamespace: selfhosted
  values:
      # -- Number of replicas
    replicaCount: 1

    image:
      # -- Image repository
      repository: m1k1o/neko
      # -- Docker pull policy
      pullPolicy: Always
      # -- Image tag
      tag: "firefox"

    # Environment variables
    env:
      # -- Screen resolution (resolution)@(fps)
      NEKO_SCREEN: 1920x1080@30
      # -- Default password for general users
      NEKO_PASSWORD: neko
      # -- Default password for administrators
      NEKO_PASSWORD_ADMIN: admin
      # -- Port range for Neko
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1

    # -- Use an existing secret with environment variables for Neko
    existingSecret: ""
    ingress:
      # -- Whether to create the ingress object
      enabled: true
      # -- Annotations for the ingress
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: neko.thekitty.zone
        external-dns.alpha.kubernetes.io/ttl: "600" #optional
      hosts:
        - # -- Hostname to access Neko
          host: neko.thekitty.zone
          paths:
            - # -- Path off the hostname to access Neko
              path: /
              # -- Path type
              pathType: ImplementationSpecific
      # -- TLS config
      # @default -- See values.yaml for an example
      tls:
       - secretName: neko-thekitty-zone-tls
         hosts:
           - neko.thekitty.zone