apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neko
  namespace: flux-system
spec:
  chart:
    spec:
      chart: neko
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
      version: '>=1.0.0'
  interval: 1h0m0s
  releaseName: neko
  targetNamespace: selfhosted
  values:
      # -- Number of replicas
    replicaCount: 1

    image:
      # -- Image repository
      repository: m1k1o/neko
      # -- Docker pull policy
      pullPolicy: Always
      # -- Image tag
      tag: "firefox"

    # Environment variables
    env:
      # -- Screen resolution (resolution)@(fps)
      NEKO_SCREEN: 1920x1080@30
      # -- Default password for general users
      NEKO_PASSWORD: neko
      # -- Default password for administrators
      NEKO_PASSWORD_ADMIN: admin
      # -- Port range for Neko
      NEKO_EPR: 52000-52100

    # -- Use an existing secret with environment variables for Neko
    existingSecret: ""