---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgCNzFov5XjO4uzITRqACJLFHdzciBNdhX3RkdqHpEqEL4P9SzbKcMTYOuTVVu30se+4huDyBHUM8JeAV1x+8S8YP1lFdfohxnXNAX1lcDMhE5Mwi+7sLuWsoqheAHZqdURpUbjF0HCLmUO6t+6uGXobf/W6c5OhtGa4emNmp4L8vY4Z5D40iSkqe0FGyhwVAn+9BH6oQEB0snLd86F6Tdq40Kb6FXWbVB48Q3ddgZLzhrl0B/7xmy/z6h5/k4FeEGtHHSHy9d2Qj5q+UKupocJilJPPZ/egCMTYmd/hcOzfla1aTk5W7FJ9PDTsdcBZqTzg/uMo9FLWw0Tg6fadC0B9YmXGnmClIodmvRFTPgr/D+983KVLo0RnJYjK0cAYWHvee45lxlAZGAS8c69bBKgW3HVUajA21JESop2WvdUyndnfdtfOlmBorn0lCQT+3FANzIlxb080JVEtZnj/kQKyv+MYtf4LU3Ktj0eohoaP+9/zzzEpmq80m5jCvXijUsnf0sGbT3UlvoUS00ezjJ/yG3Vujf7feAZHZl4ymNsrzsqAxKtkMRrVJ3LWgLZ8rlMEu4tzZ6L63kyZH08E7SDu3vaQP57oZo1eXpjpJeqh+2BC5113nG0ikVaYnaAisK2uOptTMNHg538/UXgbGFsClafmaJDB0bWAG9C+70BHA19SKyuX49ZCJvTfVzFHAQ14MamYMq7WxrzqBRAx1QoalDTg+v2LktT8gQx7Uq3TALOCM5TmvkkXRRftrxvvEMoxqMa6XRJ4WyEklc6jN7SXxFF80JITAZpSeKw3pvnGzildi14vYA5NE3vWofJK1ML8Ed0wPXIWalMiTzyrPHq1Gi4GAXYVGcRH
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: flux-system