apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  address: https://github.com/TheKitty-zone/k3s-infra
  secretRef:
    name: github
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgCoomUerXssQKoZhiF26K89JWJoWTtUUZjYXo5qGPX6lGtcjZzF929NFBjGBFI2eCk2Tz1WrCPwUEQDIIrdITNQwy00UfwnCZJl1xgVMmLK8LfN1rPmNFC0QhGeLLmW/KHebJ1cbMYB5dukp9MyzGdyzN7u7nSIzoOHu4TZfuyGy/Jm8H+ybllcz6NylXU1+65djF9K7gJ4stRAAb4nr15lybisJrOuqHN5ihumYRbHGrMsfCx1D7hl3si35wT40UIIVyoCc5/qfnE/xJg3kGyuduAIIC6OY1Qpu9KAckoe/V3M+LvoOY7Hr5ciejamR5e763nBxx67CJ1dXvMs3RCtU9kamRDAvJAebYQ/rlxrEwXA37bX1eZRujv0iP6Kl1vB8zCa/EyNUm35qliGumlvEYQAsgZgPjGu+MAHZJMgXvByXA0jIhzaNByzvXe7/cThm8wPoLINZs8kXnq8eg2nQK+BpyL2lDSyz8OqHy4qKoYUMk/ecC2LDGgO1ux/pBIGCOUd65qQ+vm+ZKNoFVuMTaYgP7IZJc43UwLoysFgUuwv52WGndNZ9841RdJUwo6+f78H68tjMmLndb2VpO+EZ4fNgag2ku44xqUn/MQ0rsv3GK1seu+8RKer6Dc5hBG//VV1zbI/AmXU/HoZLtN1LkRB4jtHqympUTGyunl45qlX725E+08Mzc1ZfQB1ankFChYQYMGni/IOGndO1rqWGYmcLGDbPWLyH2qpwmqOL84MK2OieVka
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system