---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: libreddit
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments/libreddit/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-infra
  healthChecks:
    - apiVersion: apps/v1
      kind: HelmRelease
      name: libreddit
      namespace: flux-system
  wait: true
