apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "libreddit.fullname" . }}
  labels:
    app: {{ template "libreddit.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," .Values.ingress.middlewares }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.dns.domain }}
    external-dns.alpha.kubernetes.io/ttl: {{ .Values.ingress.dns.ttl }}
spec:
  rules:
    - host: {{ .Values.ingress.dns.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "libreddit.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ template "libreddit.fullname" . }}-tls
      hosts:
        - {{ .Values.ingress.dns.domain }}

