apiVersion: v1
kind: Service
metadata:
  name: {{ template "libreddit.fullname" . }}
  labels:
    app: {{ template "libreddit.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "libreddit.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
