---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./namespace.yaml
  - ./helmrelease.yaml
  - ./ingress
  - ./podMonitors
  - ./prometheusrules
  - ./serviceMonitors
  - ./dashboards