---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./namespace.yaml
  - ./helmrelease.yaml
  - ./ingress
  - ./podMonitors
  - ./prometheusrules
  - ./serviceMonitors
  - ./dashboards
  - ./sealed-secret-alermanager-discord.yaml
  - ./alertmanager-discord.yaml