apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgB62t8jrMIOrCnA9NVEZyH/mZGQceo0PZocIX2bcEZRPRuOaM8oam3JvOxoDkkHDD/4b+BICeTR+p64Y5ZsEs54OljeL9H3PLIpDuq8oG5ZGhi6wr16i250rmQR4c4IX6OAxWvg3l3qLTxfZnQGKsJMfehO9mHzGQtHGPtpmPfU3Q2hcehMLnG1QReQbHF3s3gnqMOMzC6T/qK6zMOqZAYIUKDEEx+2xBsE0srFR2Auj3Bgyzt3+uF7OdBASUwKWbJ5TCWl5GuGEAPnthwXPXvqutTVp2jRuZ1/NiIPWeguMNwdbm9IhZBu5CCMP17uT69t0WbEfPqKlzN2AlQHR1ca1jLlXOs3R3VWrfn3haKKYVsRl3OdfeaDGf7mhNURmqXxSl6eHX+XxnH6toC7NK7N0Lvy3wagLUIhZXAs9ClsrbtNPeGmIsi3yq0L6BIZgwaFHAQnbVkHqCB4M3dy9iz1WAsl+/Z6U0DbH0Bwpnka25bocK7WL3fDLnKoj6wc18ynNJXLyZJQJf1hH3o7ta/C9ib2BuOs/alPeK59d/0OCBkjlfTELgUsLozoKqF1seNzbBQx/+xWGQ1o/L0tEdUCs5y6Kf+pouUcYbBPhnx130OCWHxwFcc63VZHDMxH5a0Ia3TjHfQ8Ngp337PN6JIJbOU4qjfdlKD8t8WnLx0kRFgBAA872+FePWB7yE3aGwny4qaTE/fiOBmDJdGm
    user: AgA3i75pHjunuH883Wdvy8/XixRvSYecWBDu2n1Rqr0dSuC8zdSx75nef9XytEr0QhnUespdkUMLSXZmX7q5v2k1m8yaitpZX1RZsTfvXururf8+ARLHLswH77mK2bDuRtPqagAg/a8bu0hwzd6dHbXi7CfvyvhlJzCtvfW+sd+jfzMiYkxEnACeZmKWXPiIN2Q3ea3AR3RN75qaHesCVLtFd3FScNgUU/zAKJgY8yBFjbBk09Tthk9c9ATq59FYdNPzE/RJzooXtgkYLaZmrB7Xy1U36lF9EEYfkRTSmYDr9G5Brybqd2yduHmxdG1bnlcEe4aHlpLVYmvEKhz0r9vVzEXPaI+28UOaVTWrG7JS0/BPF5EOLb17qiesrM84gBSLey05qIyU7bLpjWnLSUiAoNpiBBLbVuxieRG24ywCgR5SedsS6goXMI59X2ld9r9Om5FPbT1vT+CK4fYVcHLiFNsmWuTDJG0P0Tanjr1x9oY6SuS9He2Ay1Ag6iyMcXSeg7FrXfvAPWSAlGIyMxdSYYwduFSzHftzCgIpsM9HSFuA/H/XvoK4zxYEwda2PzW/dwyiWCBxX8s+lW/WR3VVIehkD0o6k4BA+8NKwtbb5Me60PcaXuDm5mhykxl/jYVGNWSGWQo2Ubj1wqn5p6Gap6E0N/q1Q4K7Du+Pm08P+m++7G1YsIq5arUgsZz3dBUKcD+uFwO5IlfbWePhH9kg01UCwtc=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring

