name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
    

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.3.1
        with:
          command: lint
          config: .github/ct.yaml
  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        run: .github/helm-docs.sh
  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.24.7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh